definitions:
  dbTable.Endpoint:
    properties:
      createdAt:
        type: string
      description:
        type: string
      id:
        type: integer
      method:
        type: string
      name:
        type: string
      path:
        type: string
      pid:
        type: integer
      type:
        enum:
        - 1
        - 2
        type: integer
      updatedAt:
        type: string
    required:
    - name
    - pid
    type: object
  dbTable.Menu:
    properties:
      component:
        type: string
      createdAt:
        type: string
      icon:
        type: string
      id:
        type: integer
      keepAlive:
        type: integer
      name:
        type: string
      path:
        type: string
      pid:
        type: integer
      roles:
        items:
          $ref: '#/definitions/dbTable.Role'
        type: array
      title:
        type: string
      type:
        type: integer
      updatedAt:
        type: string
    type: object
  dbTable.Role:
    properties:
      children:
        items:
          $ref: '#/definitions/dbTable.Role'
        type: array
      createdAt:
        description: 创建时间
        type: string
      deletedAt:
        type: string
      name:
        type: string
      parentId:
        type: integer
      roleId:
        type: integer
      updatedAt:
        description: 更新时间
        type: string
      users:
        items:
          $ref: '#/definitions/dbTable.User'
        type: array
    required:
    - name
    - parentId
    type: object
  dbTable.User:
    properties:
      active:
        description: UserRole  Role      `json:"role" gorm:"foreignKey:RoleId;references:RoleId;comment:user's
          role"`
        type: integer
      createdAt:
        type: string
      email:
        type: string
      id:
        type: integer
      password:
        type: string
      role:
        $ref: '#/definitions/dbTable.Role'
      roleId:
        type: integer
      updatedAt:
        type: string
      username:
        type: string
      uuid:
        type: string
    type: object
  request.ActiveUser:
    properties:
      code:
        type: string
    required:
    - code
    type: object
  request.DeleteUser:
    properties:
      uuid:
        description: uuid
        type: string
    required:
    - uuid
    type: object
  request.EditUser:
    properties:
      active:
        type: integer
      email:
        type: string
      role:
        type: integer
      username:
        type: string
      uuid:
        description: uuid
        type: string
    required:
    - uuid
    type: object
  request.Endpoint:
    properties:
      method:
        type: string
      path:
        type: string
    type: object
  request.Login:
    properties:
      code:
        type: string
      password:
        type: string
      username:
        type: string
    required:
    - code
    - password
    - username
    type: object
  request.RegisterUser:
    properties:
      code:
        description: use email verification instead
        type: string
      email:
        description: HeaderImg    string `json:"headerImg" gorm:"default:'https://qmplusimg.henrongyi.top/gva_header.jpg'"`
        type: string
      password:
        type: string
      role:
        type: integer
      roles:
        items:
          type: integer
        type: array
      username:
        type: string
    required:
    - code
    - email
    - password
    - username
    type: object
  request.ResetPassword:
    properties:
      code:
        type: string
      newPassword:
        type: string
    required:
    - code
    - newPassword
    type: object
  request.SendEmail:
    properties:
      email:
        type: string
    required:
    - email
    type: object
  request.UpdateCasbin:
    properties:
      endpoints:
        items:
          $ref: '#/definitions/request.Endpoint'
        type: array
      roleId:
        type: integer
    required:
    - roleId
    type: object
  response.CaptchaResponse:
    properties:
      captcha:
        type: string
    type: object
  response.Login:
    properties:
      user:
        $ref: '#/definitions/dbTable.User'
    type: object
  response.Paging:
    properties:
      list: {}
      page:
        type: integer
      pageSize:
        type: integer
      total:
        type: integer
    type: object
  response.Response:
    properties:
      data: {}
      errorCode:
        type: integer
      msg:
        type: string
    type: object
host: localhost:3000
info:
  contact:
    name: Flynn Sun
  description: Gin swagger
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Gin swagger
  version: "1.0"
paths:
  /api/public/auth/captcha:
    post:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: return base64 captcha image
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                ' msg':
                  type: string
                data:
                  $ref: '#/definitions/response.CaptchaResponse'
              type: object
      security:
      - ApiKeyAuth: []
      summary: Generate captcha image
      tags:
      - Auth
  /api/public/auth/login:
    post:
      parameters:
      - description: username, password, captcha code
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.Login'
      produces:
      - application/json
      responses:
        "200":
          description: 返回包括用户信息,token,过期时间
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  $ref: '#/definitions/response.Login'
                msg:
                  type: string
              type: object
      summary: User login
      tags:
      - User
  /api/public/auth/register:
    post:
      description: register user
      parameters:
      - description: username, password, email,captcha, role IDs
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.RegisterUser'
      produces:
      - application/json
      responses:
        "200":
          description: register user, return user info
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  $ref: '#/definitions/dbTable.User'
                msg:
                  type: string
              type: object
      summary: Register user
      tags:
      - User
  /api/public/auth/sendEmailCode:
    post:
      consumes:
      - application/json
      parameters:
      - description: email
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.SendEmail'
      produces:
      - application/json
      responses:
        "200":
          description: return send email result
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                msg:
                  type: string
              type: object
      security:
      - ApiKeyAuth: []
      summary: Send verification code email
      tags:
      - Auth
  /api/public/initDB:
    post:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: return init result msg
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                msg:
                  type: string
              type: object
      summary: initialize data
      tags:
      - Init
  /api/v1/casbin/update:
    post:
      consumes:
      - application/json
      parameters:
      - description: update privilege based on role id
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.UpdateCasbin'
      produces:
      - application/json
      responses:
        "200":
          description: update privilege based on role id
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                msg:
                  type: string
              type: object
      summary: Update role privilege
      tags:
      - Casbin
  /api/v1/endpoint/all:
    get:
      consumes:
      - application/json
      description: return all endpoints
      responses:
        "200":
          description: return all endpoints
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/dbTable.Endpoint'
                  type: array
              type: object
      summary: get all endpoints
      tags:
      - Endpoint
  /api/v1/endpoint/new:
    post:
      consumes:
      - application/json
      description: create new endpoint
      parameters:
      - description: 'Type, Name, PID, Method, Description, Path '
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/dbTable.Endpoint'
      responses:
        "200":
          description: success
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                msg:
                  type: string
              type: object
      summary: new endpoint
      tags:
      - Endpoint
  /api/v1/menu/create:
    post:
      consumes:
      - application/json
      parameters:
      - description: route path, pid, route name, component
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/dbTable.Menu'
      produces:
      - application/json
      responses:
        "200":
          description: 新增菜单
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                msg:
                  type: string
              type: object
      summary: add menu
      tags:
      - Menu
  /api/v1/menu/currentUserMenu:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: Return current user's menu list
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/dbTable.Menu'
                  type: array
                msg:
                  type: string
              type: object
      summary: get current user's menus
      tags:
      - Menu
  /api/v1/role/create:
    post:
      consumes:
      - application/json
      parameters:
      - description: name, parentId
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/dbTable.Role'
      produces:
      - application/json
      responses:
        "200":
          description: Create role, return
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  $ref: '#/definitions/dbTable.Role'
                msg:
                  type: string
              type: object
      summary: Create Role
      tags:
      - Role
  /api/v1/user/active:
    post:
      description: Active user with verification code from email
      parameters:
      - description: code
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.ActiveUser'
      produces:
      - application/json
      responses:
        "200":
          description: return activated user info
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  $ref: '#/definitions/dbTable.User'
                msg:
                  type: string
              type: object
      summary: Active user
      tags:
      - User
  /api/v1/user/delete:
    delete:
      consumes:
      - application/json
      parameters:
      - description: user uuid
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.DeleteUser'
      produces:
      - application/json
      responses:
        "200":
          description: user deleted
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                msg:
                  type: string
              type: object
      summary: delete user
      tags:
      - User
  /api/v1/user/edit:
    put:
      description: update user info
      parameters:
      - description: username, email, role ID,active, uuid
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.EditUser'
      produces:
      - application/json
      responses:
        "200":
          description: edit user, return updated user info
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  $ref: '#/definitions/dbTable.User'
                msg:
                  type: string
              type: object
      summary: Edit user info
      tags:
      - User
  /api/v1/user/resetPassword:
    put:
      parameters:
      - description: New pw, email code
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.ResetPassword'
      produces:
      - application/json
      responses:
        "200":
          description: Reset password
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                msg:
                  type: string
              type: object
      summary: Reset user password
      tags:
      - User
  /api/v1/user/userList:
    get:
      consumes:
      - application/json
      description: get user list
      parameters:
      - in: query
        name: active
        type: integer
      - description: order by desc (by default)
        in: query
        name: desc
        type: boolean
      - in: query
        name: orderBy
        type: string
      - in: query
        name: pageNumber
        type: integer
      - in: query
        name: pageSize
        type: integer
      - in: query
        name: username
        type: string
      responses:
        "200":
          description: paged user list, includes page size, page number, total counts
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  allOf:
                  - $ref: '#/definitions/response.Paging'
                  - properties:
                      data:
                        items:
                          $ref: '#/definitions/dbTable.User'
                        type: array
                    type: object
                msg:
                  type: string
              type: object
      summary: get user list
      tags:
      - User
swagger: "2.0"
