version: '3'
services:
  minio:
    image: minio/minio:latest
    container_name: blog_minio
    ports:
      - "3050:3050" # service api port
      - "3060:3060" # manage portal port
    restart: always
    volumes:
      - ./data/:/data/
      - ./config/:/root/.minio
    environment:
    - MINIO_ROOT_USER=${MINIO_ROOT_USER}
    - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":3060" --address ":3050"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3050/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
