// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSpace: typeof import('element-plus/es')['ElSpace']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IIconHome: typeof import('~icons/icon/home')['default']
    IIconVue: typeof import('~icons/icon/vue')['default']
    ISvgHome: typeof import('~icons/icon/home')['default']
    ISvgLeft_double_arrow: typeof import('~icons/icon/left_double_arrow')['default']
    ISvgLeftDoubleArrow: typeof import('~icons/icon/left-double-arrow')['default']
    ISvgRightDoubleArrow: typeof import('~icons/icon/right-double-arrow')['default']
    ISvgSetting: typeof import('~icons/icon/setting')['default']
    ISvgVue: typeof import('~icons/icon/vue')['default']
    Modal: typeof import('./src/components/shared/Modal/index.vue')['default']
    MyTable: typeof import('./src/components/shared/MyTable/index.vue')['default']
    Pagination: typeof import('./src/components/shared/Pagination/index.vue')['default']
    Permission: typeof import('./src/components/shared/Permission/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Tab: typeof import('./src/components/shared/Tab/index.vue')['default']
    VerificationCode: typeof import('./src/components/shared/VerificationCode/index.vue')['default']
  }
}
